name: Test on Push

on: [push]

jobs:
  jest:
    name: Jest Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test
      run: |
        npm i --also=dev
        npm run jest
      env:
        CI: true